name: better_player
description: Advanced video player based on video_player and Chewie. It's solves many typical use cases and it's easy to run. Now with partial IMA(Interactive Media Ads) support for Android.
version: 0.0.84
# Disabled because of warning from analyzer
# authors:
#  - Jakub Homlala <jhomlala@gmail.com>
#  - Harshit Verma <harshitverma209@gmail.com>
homepage: https://github.com/jhomlala/betterplayer
documentation: https://jhomlala.github.io/betterplayer/

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: ">=2.2.3"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  wakelock_plus: ^1.1.4
  meta: ^1.9.1
  flutter_widget_from_html_core: ^0.14.11
  visibility_detector: ^0.4.0+2
  path_provider: ^2.1.2
  collection: ^1.17.2
  xml: ^6.1.0

dev_dependencies:
  lint: ^1.8.2
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.jhomlala.better_player
        pluginClass: BetterPlayerPlugin
      ios:
        pluginClass: BetterPlayerPlugin